"""add service_form

Revision ID: 1091382b8839
Revises: d82f872e1b6f
Create Date: 2026-04-04 19:09:52.801181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1091382b8839'
down_revision: Union[str, Sequence[str], None] = 'd82f872e1b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SERVICE_FORM',
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('consent_token_id', sa.String(length=36), nullable=False),
    sa.Column('ministry_code', sa.String(), nullable=False),
    sa.Column('form_type', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('dependants', sa.Integer(), nullable=False),
    sa.Column('primary_facility', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['CITIZEN.citizen_id'], ),
    sa.ForeignKeyConstraint(['consent_token_id'], ['CONSENT_TOKEN.token_id'], ),
    sa.PrimaryKeyConstraint('form_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SERVICE_FORM')
    # ### end Alembic commands ###
