"""baseline: create citizen, voice_template, auth_event, consent_token tables

Revision ID: 684399873bc9
Revises: 
Create Date: 2026-03-30 00:07:49.357992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684399873bc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CITIZEN',
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('national_id_number', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('citizen_id')
    )
    op.create_index(op.f('ix_CITIZEN_national_id_number'), 'CITIZEN', ['national_id_number'], unique=True)
    op.create_table('AUTH_EVENT',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('voice_match_score', sa.Float(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['CITIZEN.citizen_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('CONSENT_TOKEN',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('ministry_code', sa.String(), nullable=False),
    sa.Column('data_scope', sa.String(), nullable=False),
    sa.Column('digital_signature', sa.LargeBinary(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['CITIZEN.citizen_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('VOICE_TEMPLATE',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('he_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['CITIZEN.citizen_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('VOICE_TEMPLATE')
    op.drop_table('CONSENT_TOKEN')
    op.drop_table('AUTH_EVENT')
    op.drop_index(op.f('ix_CITIZEN_national_id_number'), table_name='CITIZEN')
    op.drop_table('CITIZEN')
    # ### end Alembic commands ###
