"""add expires_at to consent_token

Revision ID: aadfd7807760
Revises: f47b92c64a23
Create Date: 2026-05-07 20:23:38.515978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadfd7807760'
down_revision: Union[str, Sequence[str], None] = 'f47b92c64a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONSENT_TOKEN', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONSENT_TOKEN', 'expires_at')
    # ### end Alembic commands ###
