"""add mosip identity columns to citizen

Revision ID: d82f872e1b6f
Revises: 684399873bc9
Create Date: 2026-04-01 16:26:00.183690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82f872e1b6f'
down_revision: Union[str, Sequence[str], None] = '684399873bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CITIZEN', sa.Column('mosip_individual_id', sa.String(), nullable=True))
    op.add_column('CITIZEN', sa.Column('identity_verified', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_CITIZEN_mosip_individual_id'), 'CITIZEN', ['mosip_individual_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CITIZEN_mosip_individual_id'), table_name='CITIZEN')
    op.drop_column('CITIZEN', 'identity_verified')
    op.drop_column('CITIZEN', 'mosip_individual_id')
    # ### end Alembic commands ###
