"""generic service_form (service_code + answers_json)

Revision ID: f47b92c64a23
Revises: 1091382b8839
Create Date: 2026-04-05 20:56:23.807067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47b92c64a23'
down_revision: Union[str, Sequence[str], None] = '1091382b8839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SERVICE_FORM', sa.Column('service_code', sa.String(), nullable=False))
    op.add_column('SERVICE_FORM', sa.Column('answers_json', sa.Text(), nullable=False))
    op.drop_column('SERVICE_FORM', 'full_name')
    op.drop_column('SERVICE_FORM', 'form_type')
    op.drop_column('SERVICE_FORM', 'dependants')
    op.drop_column('SERVICE_FORM', 'primary_facility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SERVICE_FORM', sa.Column('primary_facility', sa.VARCHAR(), nullable=False))
    op.add_column('SERVICE_FORM', sa.Column('dependants', sa.INTEGER(), nullable=False))
    op.add_column('SERVICE_FORM', sa.Column('form_type', sa.VARCHAR(), nullable=False))
    op.add_column('SERVICE_FORM', sa.Column('full_name', sa.VARCHAR(), nullable=False))
    op.drop_column('SERVICE_FORM', 'answers_json')
    op.drop_column('SERVICE_FORM', 'service_code')
    # ### end Alembic commands ###
